### ISSUE TITLE
Use JSON API instead of parsing HTML

### ISSUE THREAD

**Issue by IonBazan** [artur9010/alipaczka-cli#1]
Instead of parsing HTML at https://alipaczka.pl/pobierz.php?q={tracking_number} you could use JSON API: https://alipaczka.pl/mobileAPI2.php?number={tracking_number}.
The API provides slightly different information (no location) but still does the job. Using it would reduce  dependencies and simplify the code. WDYT?

**Comment by artur9010** [comment]
Done :)
